import { test, expect } from '@playwright/test';
test('parcours administrateur complet', async ({ page }) => {
  const id = 'contrat_de_test';
  const cloneId = `${id}_copie`;
  await page.goto('/login');
  await page.getByLabel('Utilisateur').fill('admin');
  await page.getByLabel('Mot de passe').fill('e2e-test-password');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await expect(page.getByRole('heading', { name: 'Registres contextes' })).toBeVisible();
  await page.getByRole('link', { name: 'Nouveau Registre' }).first().click();
  await page.getByLabel('Nom', { exact: true }).fill('Contrat de test');
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click();
  await expect(page).toHaveURL(/\/registries$/);
  await expect(page.getByRole('link', { name: /Contrat de test/ }).first()).toBeVisible();
  await page.getByRole('link', { name: /Contrat de test/ }).first().click();
  await expect(page).toHaveURL(new RegExp(`/registries/${id}$`));
  await page.getByRole('link', { name: 'Modifier', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`${id}/edit$`));
  await page.getByLabel('Nom', { exact: true }).fill('Contrat modifié');
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click();
  await expect(page).toHaveURL(/\/registries$/);
  await expect(page.getByRole('link', { name: /Contrat modifié/ }).first()).toBeVisible();
  await page.getByRole('link', { name: /Contrat modifié/ }).first().click();
  await expect(page.getByRole('heading', { name: 'Contrat modifié' })).toBeVisible();
  await page.getByRole('tab', { name: /Aperçu YAML/ }).click();
  await expect(page.locator('.yaml-preview')).toContainText(id);
  await page.getByRole('link', { name: 'Registries', exact: true }).last().click();
  await page.getByRole('button', { name: 'Cloner Contrat modifié' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cloner', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`${cloneId}/edit$`));
  await page.getByRole('link', { name: 'Registries', exact: true }).last().click();
  await page.getByRole('button', { name: /Supprimer Contrat modifié — copie/ }).click();
  await page.getByLabel('Je confirme la suppression de ce Registry.').check();
  await page.getByRole('button', { name: 'Supprimer définitivement' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.screenshot({ path: 'test-results/registry-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'Registres contextes' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(
    true,
  );
  await page.screenshot({ path: 'test-results/registry-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'Configuration', exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'Configuration' })).toBeVisible();
  await page.getByRole('button', { name: 'Déconnexion' }).click();
  await expect(page).toHaveURL(/login/);
});
